# Backend/docker-compose.yml
version: '3.8'

services:
  scilit-backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped